server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka

spring:
  application:
    name: microservice-gateway
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
  routes:
    loginservice.serviceId: microservice-login
    loginservice.path: /loginservice/**
    homepageservice.serviceId: microservice-homepage
    homepageservice.path: /homepageservice/**
    pgewmservice.serviceId: microservice-pgewm
    pgewmservice.path: /pgewmservice/**
  ignored-services: "*"
  prefix: /jxd



