server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka

spring:
  application:
    name: microservice-gateway
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  cloud:
    bus:
      refresh:
        enabled: true
zuul:
  routes:
    somedepart.serviceId: microservice-login
    somedepart.path: /login/**
    homepage.serviceId: microservice-homepage
    homepage.path: /homepage/**
    pgewm.serviceId: microservice-pgewm
    pgewm.path: /pgewm/**
  ignored-services: "*"
  prefix: /jxd
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      excution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000