server:
  port: 8600
eureka:
  instance:
    hostname: mircroserice-registory
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8000.com:8600/eureka