server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka

spring:
  application:
    name: microservice-gateway
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: false
  routes:
    somedepart.serviceId: microservice-login
    somedepart.path: /login/**
    homepage.serviceId: microservice-homepage
    homepage.path: /homepage/**
    pgewm.serviceId: microservice-pgewm
    pgewm.path: /pgewm/**
  ignored-services: "*"
  prefix: /jxd



