server:
  port: 8087
spring:
  profiles: dev
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: roger
  application:
    name: appEureka
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.decrptor.sql.BasicBinder: trace
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.sgcc.pms.provider: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8400/eureka
info:
  company.name: com.sgcc.pms.jxd
  company.tel: 17627032752
  comany.address: china
  author.name: white
  app.des: provide03
 
---
server:
  port: 8089
spring:
  profiles: test
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: roger
  application:
    name: appEureka
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.decrptor.sql.BasicBinder: trace
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.sgcc.pms.provider: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka
info:
  company.name: com.sgcc.pms.jxd
  company.tel: 17627032752
  comany.address: china
  author.name: white
  app.des: provide03
