spring:
  application:
    name: config-dev
  profiles: dev

server:
  port: 8400
eureka:
  instance:
    hostname: eureka8100.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8100.com:8400/eureka

---
spring:
  application:
    name: config-test
  profiles: test
server:
  port: 8500
eureka:
  instance:
    hostname: eureka8100.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8200.com:8500/eureka
