server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka

spring:
  application:
    name: microservice-gateway
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
  routes:
    loginservice.serviceId: microservice-login
    loginservice.path: /loginservice/**
    homepageservice.serviceId: microservice-homepage
    homepageservice.path: /homepageservice/**
    pgewmservice.serviceId: microservice-pgewm
    pgewmservice.path: /pgewmservice/**
  ignored-services: "*"
  prefix: /jxd



